### ISSUE TITLE
Warning "Entity None" with 2024.01

### ISSUE THREAD

**Issue by Gloomyeye** [tschamm/boschshc-hass#141]
I got the following warning with the latest version of 2024.01:

```
 Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1520
First occurred: 05:22:34 (35 occurrences)
Last logged: 05:22:35

    Entity None (<class 'custom_components.bosch_shc.climate.ClimateControl'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE|PRESET_MODE: 17>, please create a bug report at https://github.com/tschamm/boschshc-hass/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
```

**Comment by tschamm** [comment]
I have the same issue, however I think it is more a bug in the HA climate platform, as I am already using ClimateEntityFeature. I will have another look the next days.

**Comment by Gloomyeye** [comment]
Fixed with 0.4.78

**Comment by lesgrebe** [comment]
Hi,

Updatet to 0.4.78 an many of these warning are gone but one warning is still present:

Logger: homeassistant.components.light
Source: components/light/__init__.py:1194
Integration: Licht (documentation, issues)
First occurred: 19:30:19 (2 occurrences)
Last logged: 19:30:19

Entity None (<class 'custom_components.bosch_shc.light.LightSwitch'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 19> and color modes, please create a bug report at https://github.com/tschamm/boschshc-hass/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

Systeminfo:
![image](https://github.com/tschamm/boschshc-hass/assets/37287548/c9784a45-22de-4f0f-8bec-f7c6207ceaee)

Regards
Michi
