### ISSUE TITLE
Error Code 400 when switching multiple instances of Bosch Thermostat II in a scene

### ISSUE THREAD

**Issue by fritut08** [tschamm/boschshc-hass#73]
I successfully installed this integration in Home Assistant and configured my 5 Bosch Thermostats II. so that I can set the desired room climate temperature or mode (off, manual, automatic) without a problem for individual thermostats.
However, I created scenes to change the mode of all 5 thermostats at once and when I trigger the scene that switches the thermostats off, I get the following error:
`Fehler beim Aufrufen des Dienstes scene/turn_on. SHC Error (message: API call returned non-OK result (code 400)!: b'{"@type"."JsonRestExecutionResponseEntity","errorCode":"WRONG_THERMOSTAT_GROUP_MODE","statusCode":400}')`
(The first few words are German and translate to "Error while calling the service...")
The thermostats are all switched offed despite this error message. But the error makes it impossible to use the scene within an automation because those stop as soon as an error occurs.
Oddly, the other scenes that switch all thermostats to automatic or manual mode work without resulting in an error.

Does anyone know what error code 400 means and whether I can do something about it?

**Comment by fritut08** [comment]
This is a picture of the log after the error occured. The automation that makes use of the scene is named "Durchlüften Thermostate".

![grafik](https://user-images.githubusercontent.com/53369972/206308561-cdea7590-9a9d-4f6a-971b-46a6591bb57b.png)

**Comment by tschamm** [comment]
Hi @fritut08 
You may ask in the [Bosch Smart Home](https://github.com/BoschSmartHome/bosch-shc-api-docs) what is the root cause of the error "WRONG_THERMOSTAT_GROUP_MODE". This may help us to understand better why this happens.

**Comment by fritut08** [comment]
@tschamm 
Thanks for the reply. I did so [here](https://github.com/BoschSmartHome/bosch-shc-api-docs/issues/69).

**Comment by Hellfirefox** [comment]
I put three Thermostat IIs into operation today. One is in a room with a Bosch window sensor. When the window is open and the window sensor is set to open, I get the same error. 
If the window was closed, the error message did not appear.
I don't know if the description helps, but I suspect it has to do with the underfloor heating shutting off when the window is open.

**Comment by tschamm** [comment]
I can confirm this error. 
* putting the device in eco mode (opening a window in the same room)
* adjusting the temperature via API - all ok, device stays in eco mode
* adjust the temperature manually on the thermostat, eco mode is stopped and temperature is set to desired value
* adjusting the temperature via API (window is still open), `WRONG_THERMOSTAT_GROUP_MODE` error pops up

**Comment by mosandlt** [comment]
Fixed in **0.5.1**: setting a temperature while the room is in the scheduled/AUTO mode now switches the room to MANUAL first (when no HVAC mode is passed in the call), so the SHC no longer rejects it with HTTP 400 `WRONG_THERMOSTAT_GROUP_MODE` — matching the Bosch app. Please update via HACS. Closing — reopen if it persists.

**Comment by sid3windr** [comment]
I still get "WRONG_THERMOSTAT_GROUP_MODE" when trying to set temperature on a room Climate Control entity.

`2026-07-01 13:03:48.758 WARNING (MainThread) [custom_components.bosch_shc] Failed to set temperature on device Living room: SHC Error (message: API call returned non-OK result (code 400)!: b'{"@type":"JsonRestExceptionResponseEntity","errorCode":"WRONG_THERMOSTAT_GROUP_MODE","statusCode":400}')`

I am on 0.9.2.

**Comment by mosandlt** [comment]
Thanks for reporting @sid3windr — reopening to track this separately from the original scene/AUTOMATIC case (which was fixed in 0.5.1).

Looking at the current code, `async_set_temperature` only switches the room out of `AUTOMATIC` mode before writing the setpoint — it doesn't handle the room's `low` (eco/reduced) state. Earlier in this thread @tschamm diagnosed that exact combination in 2023: when a room is in eco/reduced mode (e.g. triggered by an open window), the SHC rejects setpoint writes with the same `WRONG_THERMOSTAT_GROUP_MODE` error, independent of `operationMode`.

Could you help confirm whether that's what's happening here?
- Was a window/door open in that room, or was it otherwise in a reduced/eco state, when you hit the error?
- If you have debug logging enabled (`custom_components.bosch_shc` / `boschshcpy` at `debug`), could you share the raw `RoomClimateControl` service state (`operationMode`, `low`, `setpointTemperature`) for the "Living room" device right before the failed call?

That'll tell us whether the fix is to also clear `low` before writing the setpoint (regardless of `operationMode`).

**Comment by sid3windr** [comment]
Hi, indeed, that is a very good point. I was wondering why I only noticed that error today, it "must" have been there before (I'm setting temp from an automation). But this is with a window open, so indeed the mode must have been eco, and that would be the reason.

**Comment by mosandlt** [comment]
Confirmed — that's a distinct case from the AUTOMATIC one this issue was originally filed for. `async_set_temperature` only cleared `operationMode=AUTOMATIC` before writing the setpoint; it never cleared the room's `low` (eco/reduced) flag independently, which the SHC also rejects with `WRONG_THERMOSTAT_GROUP_MODE` regardless of `operationMode` — matching @tschamm's 2023 diagnosis and @Hellfirefox's floor-heating report above.

Fixed in **0.9.3**: `async_set_temperature` now clears `low` itself before writing the setpoint whenever the device reports it (keyed on the raw `low` field, not `supports_eco`, so floor-heating rooms without a dedicated eco preset are covered too). Please update via HACS and let us know if you still see it.

https://github.com/tschamm/boschshc-hass/releases/tag/v0.9.3

**Comment by mosandlt** [comment]
No further reports since the 0.9.3 fix (clearing `low`/eco before the setpoint write) — current release is 0.10.6, several versions past it. Closing — reopen if it resurfaces.
